// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import 'dotenv/config';
import path from 'node:path';
import { defineConfig, env } from 'prisma/config';

/** SQLite paths in DATABASE_URL are relative to project root (not prisma/). */
function resolveDatabaseUrl(url: string): string {
  if (!url.startsWith('file:')) return url;
  const filePath = url.slice('file:'.length);
  if (path.isAbsolute(filePath)) return url;
  const normalized = filePath.replace(/^\.\//, '');
  return `file:${path.join(process.cwd(), normalized)}`;
}

export default defineConfig({
  schema: 'prisma/schema.prisma',
  migrations: {
    path: 'prisma/migrations',
  },
  engine: 'classic',
  datasource: {
    url: resolveDatabaseUrl(env('DATABASE_URL')),
  },
});
